###
# @name plugins/<%= plugin_name %>/index.coffee
# Autogenerated by pinkhippos:seneca_plugin
###

module.exports = (options)->
  plugin = '<%= plugin_name%>'
  commands = [
    # Add cmds here
  ]
  for cmd in commands
    pattern_string = "role:#{plugin},cmd:#{cmd}"
    @add pattern_string, require "#{__dirname}/#{cmd}"
  plugin
