###*
 # @name <%= command %>
 # @description
 # Auto Generated by pinkhippos:seneca_action
###
module.exports = (args, done)->
  {SOME_REQUIRED_ARG} = args
  #Check for any required arguments here
  if !SOME_REQUIRED_ARG
    err_opts =
      role: 'util'
      cmd: 'missing_args'
      given: @util.clean args
    @act err_opts, (err, response)->
      if err or response.err
        done null, {
          seneca_err: err
          action_err: err
        }
      else
        done null, err: response.data
  else
    # Do the logic of the action here
    DUMMY_ACTION =
      role: 'foo'
      cmd: 'bar'
    @act add_opts, (err, response)->
      if err
        done err
      else if response.err
        done null, err: response.err
      else
        done null, data: response.data
